export const IDummyContent = [
    {        
        "id": 0,
        "title" : "The Beginning After The End",
        "type" : "MANHWA",
        "genre" : "High Fantasy, Fantasy Fiction, Fairy Tale",
        "summary" : "The Beginning After The End follows the life of the late King Grey after his untimely and mysterious death. Reborn as Arthur Leywin, he seeks to correct his past mistakes in the vibrant new continent of Dicathen, a world of magic and fantastical creatures.",
        "status" : "Ongoing",
        "author" : "Turtleme",
        "img_link" : "https://images.thalia.media/-/BF2000-2000/c6e4d86a035d401bbfa4c1cca1a348d6/the-beginning-after-the-end-vol-1-taschenbuch-turtleme-englisch.jpeg",
        "ratings" : '* * * * *',
        "chapters" : [
            'Chapter 1',
            'Chapter 2',
            'Chapter 3',
            'Chapter 4',
            'Chapter 5',
                    ]
    },
    {
        "id": 1,
        "title" : "Damn Reincarnation",
        "type" : "MANHWA",
        "genre" : "Action, Shounen, Fantasy, Adventure, Reincarnation",
        "summary" : "Hamel, a warrior who traveled with his colleagues to exterminate the devil. Unfortunately, he died just before the battle with the devil started. “Yes.” What the hell? He was reborn as the descendant of his fellow warrior, Vermouth.",
        "status" : "Ongoing",
        "author" : "Turtleme",
        "img_link" : "https://www.asurascans.com/wp-content/uploads/2022/06/Damn_ReincarnationCover003.png",
        "ratings" : '* * * * *',
        "chapters" : [
            'Chapter 1',
            'Chapter 2',
            'Chapter 3',
            'Chapter 4',
            'Chapter 5',
                    ]
    },
    {
        "id": 2,
        "title" : "Relife Player",
        "type" : "MANHWA",
        "genre" : "High Fantasy, Fantasy Fiction, Fairy Tale",
        "summary" : "The Beginning After The End follows the life of the late King Grey after his untimely and mysterious death. Reborn as Arthur Leywin, he seeks to correct his past mistakes in the vibrant new continent of Dicathen, a world of magic and fantastical creatures.",
        "status" : "Ongoing",
        "author" : "Turtleme",
        "img_link" : "https://www.asurascans.com/wp-content/uploads/2022/12/RelifePlayerCover03.png",
        "ratings" : '* * * * *',
        "chapters" : [
            'Chapter 1',
            'Chapter 2',
            'Chapter 3',
            'Chapter 4',
            'Chapter 5',
                    ]
    },
    {
        "id": 3,
        "title" : "Reaper of the Drifting Moon",
        "type" : "MANHWA",
        "genre" : "High Fantasy, Fantasy Fiction, Fairy Tale",
        "summary" : "He’s in the deepest part of the Jianghu. Keep your eyes wide open if you do not wish to get dragged into the abyss.",
        "status" : "Ongoing",
        "author" : "Turtleme",
        "img_link" : "https://www.asurascans.com/wp-content/uploads/2022/07/Reaper-Moon-Cover-Animation_Compressed.gif",
        "ratings" : '* * * * *',
        "chapters" : [
            'Chapter 1',
            'Chapter 2',
            'Chapter 3',
            'Chapter 4',
            'Chapter 5',
                    ]
    },
    {
        "id": 4,
        "title" : "Standard Reincarnation",
        "type" : "MANHWA",
        "genre" : "Action, Fantasy, Adventure, Martial Arts",
        "summary" : "The greatest martial family, Samion. Daven, a member of the Samion family, is a one-armed martial soldier without a right arm. Despite the ridicule and contempt he got for only having a left arm, he surpassed the direct line of the Samion family like a genius. However, he got betrayed by his family and parents in the end, thus meeting a poor end. But, he was reincarnated.",
        "status" : "Ongoing",
        "author" : "Kim Pyeongbeom",
        "img_link" : "https://www.asurascans.com/wp-content/uploads/2022/08/standardofReCover03.png",
        "ratings" : '* * * * *',
        "chapters" : [
            'Chapter 1',
            'Chapter 2',
            'Chapter 3',
            'Chapter 4',
            'Chapter 5',
                    ]
    },
    {
        "id": 5,
        "title" : "Demon Lord's Martial Arts Ascension",
        "type" : "MANHWA",
        "genre" : "High Fantasy, Fantasy Fiction, Fairy Tale",
        "summary" : "Demon Lord. That’s… What they used to call me in my past life, before I became human.",
        "status" : "Ongoing",
        "author" : "Med",
        "img_link" : "https://www.asurascans.com/wp-content/uploads/2022/11/DemonLordCover02.png",
        "ratings" : '* * * * *',
        "chapters" : [
            'Chapter 1',
            'Chapter 2',
            'Chapter 3',
            'Chapter 4',
            'Chapter 5',
                    ]
    },
    {
        "id": 6,
        "title" : "Shadowless Night",
        "type" : "MANHWA",
        "genre" : "Action, Adventure, Fantasy, Romance",
        "summary" : "When you enter the deep forest, you will be devoured by the shadow. The shadow in the forest moves when no one is looking. In the deep forest, there is a shadow that mimics humans. The shadow speaks.",
        "status" : "Ongoing",
        "author" : "Med",
        "img_link" : "https://www.asurascans.com/wp-content/uploads/2022/08/ShadowlessNightCover03-1.png",
        "ratings" : '* * * * *',
        "chapters" : [
            'Chapter 1',
            'Chapter 2',
            'Chapter 3',
            'Chapter 4',
            'Chapter 5',
                    ]
    },
    {
        "id": 7,
        "title" : "Existence",
        "type" : "MANHWA",
        "genre" : "Action, Overpowered, Fantasy, Adventure",
        "summary" : "One day, it was a herd of ants, and another day, it was a large dinosaur. This was the last reincarnation of a being that had experienced tens of thousands of reincarnations and lives.",
        "status" : "Ongoing",
        "author" : "Med",
        "img_link" : "https://www.asurascans.com/wp-content/uploads/2022/08/existenceCover01.png",
        "ratings" : '* * * * *',
        "chapters" : [
            'Chapter 1',
            'Chapter 2',
            'Chapter 3',
            'Chapter 4',
            'Chapter 5',
                    ]
    },
]